ALTER TABLE ai_brand_memory ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_content_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_quality_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_calendar_draft_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_community_reply_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_report_drafts ENABLE ROW LEVEL SECURITY;
ALTER TABLE ai_approval_audit_events ENABLE ROW LEVEL SECURITY;
