apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-analysis
  labels:
    app: content-analysis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: content-analysis
  template:
    metadata:
      labels:
        app: content-analysis
    spec:
      containers:
        - name: content-analysis
          image: ghcr.io/qurbaneliii/aria-content-analysis:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: aria-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: content-analysis
spec:
  selector:
    app: content-analysis
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
