apiVersion: apps/v1
kind: Deployment
metadata:
  name: visual-understanding
  labels:
    app: visual-understanding
spec:
  replicas: 2
  selector:
    matchLabels:
      app: visual-understanding
  template:
    metadata:
      labels:
        app: visual-understanding
    spec:
      containers:
        - name: visual-understanding
          image: ghcr.io/qurbaneliii/aria-visual-understanding:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: aria-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: visual-understanding
spec:
  selector:
    app: visual-understanding
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
